name: wikwok
description: "Doomscroll your way to endless knowledge."
publish_to: 'none'

version: 1.1.1+3

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  package_info_plus: ^9.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
