name: Bug
description: Report a bug
title: "Bug: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Fill in the fields below to report a bug.
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      placeholder: Describe the steps to reproduce the bug
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
