name: 'Setup Flutter SDK'
description: 'Setup the Flutter SDK.'
runs:
  using: "composite"
  steps:
    - id: flutter-sdk-version
      uses: ./.github/actions/get-flutter-sdk-version

    - name: Setup Flutter (${{ steps.flutter-sdk-version.outputs.version }})
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.flutter-sdk-version.outputs.version }}
        cache: true
