name: Get Flutter SDK Version

on:
  workflow_call:
    outputs:
      version:
        description: "The Flutter SDK version"
        value: ${{ jobs.get.outputs.version }}

jobs:
  get:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get.outputs.version }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - id: get
        run: |
          version=$(python3 _scripts/get_flutter_sdk_version.py --file .fvmrc)
          echo "version=$version" >> $GITHUB_OUTPUT
