name: On release published

on:
  release:
    types: [ published, edited ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set APP_VERSION
        run: |
          VERSION=${{ github.ref_name }}
          APP_VERSION=${VERSION#v}
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.5

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Delete test files
        run: find . -name '*_test.dart' -delete

      - name: Set up keystore
        env:
          KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          echo $KEYSTORE_JKS | base64 -d > android/app/keystore.jks
          echo $KEY_PROPERTIES | base64 -d > android/key.properties


      - name: '📦 Build apk'
        run: |
          flutter build apk --release --target-platform android-arm64
          mv build/app/outputs/flutter-apk/app-release.apk .
          mv app-release.apk wikwok-${{ env.APP_VERSION }}.apk

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: apk
          path: wikwok-${{ env.APP_VERSION }}.apk

  upload-to-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set APP_VERSION
        run: |
          VERSION=${{ github.ref_name }}
          APP_VERSION=${VERSION#v}
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: apk

      - name: Upload APK to release
        run: |
          gh release upload ${{github.event.release.tag_name}} wikwok-${{ env.APP_VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash